# Copyright (c) 2020 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Process Test Results

# Either a daily based on schedule/cron or only on tag push
on:
  schedule:
    - cron:  '50 06 * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: checkout
      uses: actions/checkout@v2

      #    - name: install-pkgs
      #run: |
      #  sudo apt-get install -y ninja-build doxygen

    - name: cache-pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-test-pip

    - name: install-pip
      run: |
        pip3 install wheel setuptools
        pip3 install junit2html

    - name: Download Versions
      id: results
      run: |
        aws s3 cp s3://testing.zephyrproject.org/daily_tests/versions.json .
        latest=`cat versions.json |jq -r  '.[-1] '`
        echo ::set-output name=version::${latest};
        echo "Latest is ${latest}";
        mkdir -p ${latest} output/${latest}
        aws s3 sync --quiet s3://testing.zephyrproject.org/daily_tests/${latest}  ${latest}
        ./scripts/merge.py -c ${latest} -t ${latest}/ -o output/${latest}/report

        # copy files from git tree
        if [ -d "results/${latest}" ]; then
          for f in `ls -1 results/${latest}`; do
            echo "Working on ${f}.."
            ./scripts/convert.py --junit-file results/${latest}/${f} --output-dir output/${latest}/report/
          done
        fi

        cd output/${latest}/report;
        ~/.local/bin/junit2html --report-matrix index.html *.xml
        cd ..
        aws s3 sync --quiet report s3://testing.zephyrproject.org/daily_tests/${latest}/report


    - name: Upload Results
      uses: actions/upload-artifact@master
      continue-on-error: True
      with:
        name: results-${{ steps.results.outputs.version }}
        path: output/

